apiVersion: v1
data:
  GOOGLE_APPLICATION_CREDENTIALS: "/secret/creds.json"
  DB_FILE: "./db/chonkers.db"
  BUCKET_ID: "jch-chonkers-static-assets"
  PORT: "8080"

kind: ConfigMap
metadata:
  name: chonker-map
