apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: chonkers
  name: chonkers-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chonkers
  strategy: {}
  template:
    metadata:
      labels:
        app: chonkers
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        name: chonkers-service
        volumeMounts:
        - name: secret-volume
          mountPath: /app
          readOnly: true
        envFrom:
        - configMapRef:
          name: chonker-map
      volumes:
      - name: secret-volume
        secret:
          secretName: google-api-creds
status: {}
