apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chonkers
  name: chonkers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chonkers
  strategy: {}
  template:
    metadata:
      labels:
        app: chonkers
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/winged-plate-378113/chonky-repository/chonkers-service:f53de1fb320986bf29c346271d22336fb957c366
        name: chonkers-service
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: /secret
          readOnly: true
        envFrom:
        - configMapRef:
            name: chonker-map
      volumes:
      - name: secret-volume
        secret:
          secretName: google-api-creds
status: {}
