apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-17T21:26:30Z"
  generation: 1
  labels:
    app: chonkers
  name: chonkers
  namespace: default
  resourceVersion: "2162151"
  uid: aa5bbb1d-feba-4ca3-ac5a-0b5de62f6482
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chonkers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chonkers
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/winged-plate-378113/chonky-repository/chonkers-service:3e9c68a8af2f670753c3aa1d3689f362cf07e4ed
        imagePullPolicy: IfNotPresent
        name: chonkers-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
