apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: chonkers
  name: chonkers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chonkers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chonkers
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        name: chonkers-service
        resources: {}
status: {}
